name: AzureLoginSample

on:
  push:
    branches:
      - main  # Adjust the branch name as needed
permissions:
  id-token: write
  contents: read     

jobs:
  login_to_azure:
    runs-on: ubuntu-latest

    steps:
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: '${{secrets.AZURE_CREDENTIALS}}'
        enable-AzPSSession: false
        environment: azurecloud
        allow-no-subscriptions: false
        audience: api://AzureADTokenExchange
        auth-type: SERVICE_PRINCIPAL
